global using Xunit;
global using Moq;
global using FluentAssertions;
global using BikolTwitter.Database;
global using BikolTwitter.Entities;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.EntityFrameworkCore;
global using System.Net;
global using Xunit.Abstractions;