// <auto-generated />
using BikolTwitter.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikolTwitter.Migrations
{
    [DbContext(typeof(BikolTwitterDbContext))]
    [Migration("20230114163652_ChangeBikolSubIdTypeToInt")]
    partial class ChangeBikolSubIdTypeToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("BikolTwitter.Entities.BikolSub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TwitterUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BikolSubs");
                });
#pragma warning restore 612, 618
        }
    }
}
